# Generated by Django 4.2.7 on 2025-09-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours used in current cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_distance', models.FloatField(blank=True, help_text='Total distance in miles', null=True)),
                ('estimated_duration', models.FloatField(blank=True, help_text='Estimated duration in hours', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('point_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('dropoff', 'Dropoff'), ('end', 'End')], max_length=50)),
                ('sequence', models.IntegerField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0, help_text='Hours spent at this location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='eld_app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('driver_name', models.CharField(default='Driver', max_length=255)),
                ('carrier_name', models.CharField(default='Carrier', max_length=255)),
                ('vehicle_number', models.CharField(default='Truck-001', max_length=50)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('total_on_duty_7_days', models.FloatField(default=0)),
                ('hours_available_70hr', models.FloatField(default=0)),
                ('total_on_duty_5_days', models.FloatField(default=0)),
                ('total_on_duty_6_days', models.FloatField(default=0)),
                ('hours_available_60hr', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='eld_app.trip')),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (not driving)')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('eld_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_statuses', to='eld_app.eldlog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
